### ISSUE TITLE
HTML5 example and e-entity

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-workflow-editor#23]
When I load the HTML 5 example and then perform e-Entity enrichment with default values then the annotation gets broken. It repeats the text multiple times, being followed by "@en" each time. The first two times the text is completely wrapped with one long annotation.

**Comment by ArneBinder** [comment]
@jnehring I can not reproduce this. Perhaps it is already fixed by [this](https://github.com/freme-project/freme-ner/issues/94)?

**Comment by jnehring** [comment]
The error still occurs on the [live version](http://api.freme-project.eu/freme-workflow-editor/).

In this screenshot I have marked the places where the text repeats.

![image](https://cloud.githubusercontent.com/assets/10537540/15666533/899314ea-2711-11e6-9a6b-e928580a4242.png)

**Comment by ArneBinder** [comment]
I can not reproduce this on the dev version, so I think this will be fixed after the next release on live also.

**Comment by jnehring** [comment]
This bug was fixed by fixing a problem in the backend.
